name: Playwright Scheduled Run

on:
  schedule:
    - cron: '40 10 * * *'   # ⏰ Runs
  workflow_dispatch:        # ✅ Optional: Manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Playwright Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2t64 libgbm1 libxshmfence1
      

    - name: Verify Gradle is installed
      run: gradle --version

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run TestNG Tests using Gradle Wrapper
      run: ./gradlew test
      
    - name: View Gradle Test Logs
      run: |
        cat build/reports/tests/test/index.html   # View the test results HTML file
        cat build/test-results/test/TEST-*.xml   # View the XML results if needed

