name: Playwright Scheduled Run

on:
  schedule:
    # Friday and Saturday at 14:10 BST (13:10 UTC), 15:10 BST (14:10 UTC), and 16:10 BST (15:10 UTC)
    - cron: '10 13 * * 5,6'
    - cron: '10 14 * * 5,6'
    - cron: '10 15 * * 5,6'
    # Monday to Thursday and Sunday at 15:10 BST (14:10 UTC) and 16:10 BST (15:10 UTC)
    - cron: '10 14 * * 0,1,2,3,4' # Sunday (0) to Thursday (4)
    - cron: '10 15 * * 0,1,2,3,4'
    - cron: '10 12 * * 0,1,2,3,4'
    - cron: '10 13 * * 0,1,2,3,4'
  workflow_dispatch:      # ✅ Optional: Manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Runner Time (UTC)
        run: date -u

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Playwright Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2t64 libgbm1 libxshmfence1

      - name: Verify Gradle is installed
        run: gradle --version

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run TestNG Tests using Gradle Wrapper
        run: ./gradlew test

      - name: View Gradle Test Logs
        run: |
          cat build/reports/tests/test/index.html    # View the test results HTML file
          cat build/test-results/test/TEST-*.xml    # View the XML results if needed